/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugLayoutDebugRouteImport } from './routes/_debug-layout/debug'
import { Route as DebugLayoutPostPageIdDebugRouteImport } from './routes/_debug-layout/post/$pageId/debug'
import { Route as DebugLayoutRouteRouteImport } from './routes/_debug-layout/route'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_default-layout/index'
import { Route as DefaultLayoutPostPageIdImageRouteImport } from './routes/_default-layout/post/$pageId/image'
import { Route as DefaultLayoutPostPageIdRouteRouteImport } from './routes/_default-layout/post/$pageId/route'
import { Route as DefaultLayoutRouteRouteImport } from './routes/_default-layout/route'
import { Route as PlaygroundOgImageRouteImport } from './routes/playground/og-image'
import { Route as PlaygroundSsrRouteImport } from './routes/playground/ssr'

const DefaultLayoutRouteRoute = DefaultLayoutRouteRouteImport.update({
  id: '/_default-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutRouteRoute = DebugLayoutRouteRouteImport.update({
  id: '/_debug-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRouteRoute,
} as any)
const PlaygroundSsrRoute = PlaygroundSsrRouteImport.update({
  id: '/playground/ssr',
  path: '/playground/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundOgImageRoute = PlaygroundOgImageRouteImport.update({
  id: '/playground/og-image',
  path: '/playground/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutDebugRoute = DebugLayoutDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DebugLayoutRouteRoute,
} as any)
const DefaultLayoutPostPageIdRouteRoute = DefaultLayoutPostPageIdRouteRouteImport.update({
  id: '/post/$pageId',
  path: '/post/$pageId',
  getParentRoute: () => DefaultLayoutRouteRoute,
} as any)
const DefaultLayoutPostPageIdImageRoute = DefaultLayoutPostPageIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => DefaultLayoutPostPageIdRouteRoute,
} as any)
const DebugLayoutPostPageIdDebugRoute = DebugLayoutPostPageIdDebugRouteImport.update({
  id: '/post/$pageId/debug',
  path: '/post/$pageId/debug',
  getParentRoute: () => DebugLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/post/$pageId': typeof DefaultLayoutPostPageIdRouteRouteWithChildren
  '/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/post/$pageId': typeof DefaultLayoutPostPageIdRouteRouteWithChildren
  '/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_debug-layout': typeof DebugLayoutRouteRouteWithChildren
  '/_default-layout': typeof DefaultLayoutRouteRouteWithChildren
  '/_debug-layout/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/_default-layout/': typeof DefaultLayoutIndexRoute
  '/_default-layout/post/$pageId': typeof DefaultLayoutPostPageIdRouteRouteWithChildren
  '/_debug-layout/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/_default-layout/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/post/$pageId'
    | '/post/$pageId/debug'
    | '/post/$pageId/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/post/$pageId'
    | '/post/$pageId/debug'
    | '/post/$pageId/image'
  id:
    | '__root__'
    | '/_debug-layout'
    | '/_default-layout'
    | '/_debug-layout/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/_default-layout/'
    | '/_default-layout/post/$pageId'
    | '/_debug-layout/post/$pageId/debug'
    | '/_default-layout/post/$pageId/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DebugLayoutRouteRoute: typeof DebugLayoutRouteRouteWithChildren
  DefaultLayoutRouteRoute: typeof DefaultLayoutRouteRouteWithChildren
  PlaygroundOgImageRoute: typeof PlaygroundOgImageRoute
  PlaygroundSsrRoute: typeof PlaygroundSsrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default-layout': {
      id: '/_default-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout': {
      id: '/_debug-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DebugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default-layout/': {
      id: '/_default-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/playground/ssr': {
      id: '/playground/ssr'
      path: '/playground/ssr'
      fullPath: '/playground/ssr'
      preLoaderRoute: typeof PlaygroundSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/og-image': {
      id: '/playground/og-image'
      path: '/playground/og-image'
      fullPath: '/playground/og-image'
      preLoaderRoute: typeof PlaygroundOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout/debug': {
      id: '/_debug-layout/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLayoutDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
    '/_default-layout/post/$pageId': {
      id: '/_default-layout/post/$pageId'
      path: '/post/$pageId'
      fullPath: '/post/$pageId'
      preLoaderRoute: typeof DefaultLayoutPostPageIdRouteRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/_default-layout/post/$pageId/image': {
      id: '/_default-layout/post/$pageId/image'
      path: '/image'
      fullPath: '/post/$pageId/image'
      preLoaderRoute: typeof DefaultLayoutPostPageIdImageRouteImport
      parentRoute: typeof DefaultLayoutPostPageIdRouteRoute
    }
    '/_debug-layout/post/$pageId/debug': {
      id: '/_debug-layout/post/$pageId/debug'
      path: '/post/$pageId/debug'
      fullPath: '/post/$pageId/debug'
      preLoaderRoute: typeof DebugLayoutPostPageIdDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
  }
}

interface DebugLayoutRouteRouteChildren {
  DebugLayoutDebugRoute: typeof DebugLayoutDebugRoute
  DebugLayoutPostPageIdDebugRoute: typeof DebugLayoutPostPageIdDebugRoute
}

const DebugLayoutRouteRouteChildren: DebugLayoutRouteRouteChildren = {
  DebugLayoutDebugRoute: DebugLayoutDebugRoute,
  DebugLayoutPostPageIdDebugRoute: DebugLayoutPostPageIdDebugRoute,
}

const DebugLayoutRouteRouteWithChildren = DebugLayoutRouteRoute._addFileChildren(
  DebugLayoutRouteRouteChildren,
)

interface DefaultLayoutPostPageIdRouteRouteChildren {
  DefaultLayoutPostPageIdImageRoute: typeof DefaultLayoutPostPageIdImageRoute
}

const DefaultLayoutPostPageIdRouteRouteChildren: DefaultLayoutPostPageIdRouteRouteChildren = {
  DefaultLayoutPostPageIdImageRoute: DefaultLayoutPostPageIdImageRoute,
}

const DefaultLayoutPostPageIdRouteRouteWithChildren =
  DefaultLayoutPostPageIdRouteRoute._addFileChildren(DefaultLayoutPostPageIdRouteRouteChildren)

interface DefaultLayoutRouteRouteChildren {
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
  DefaultLayoutPostPageIdRouteRoute: typeof DefaultLayoutPostPageIdRouteRouteWithChildren
}

const DefaultLayoutRouteRouteChildren: DefaultLayoutRouteRouteChildren = {
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
  DefaultLayoutPostPageIdRouteRoute: DefaultLayoutPostPageIdRouteRouteWithChildren,
}

const DefaultLayoutRouteRouteWithChildren = DefaultLayoutRouteRoute._addFileChildren(
  DefaultLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DebugLayoutRouteRoute: DebugLayoutRouteRouteWithChildren,
  DefaultLayoutRouteRoute: DefaultLayoutRouteRouteWithChildren,
  PlaygroundOgImageRoute: PlaygroundOgImageRoute,
  PlaygroundSsrRoute: PlaygroundSsrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from '@tanstack/react-start'
import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
