/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultLayoutRouteRouteImport } from './routes/_default-layout/route'
import { Route as DebugLayoutRouteRouteImport } from './routes/_debug-layout/route'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_default-layout/index'
import { Route as PlaygroundSsrRouteImport } from './routes/playground/ssr'
import { Route as PlaygroundOgImageRouteImport } from './routes/playground/og-image'
import { Route as DebugLayoutDebugRouteImport } from './routes/_debug-layout/debug'
import { Route as DefaultLayoutSlugOrIdIndexRouteImport } from './routes/_default-layout/$slugOrId/index'
import { Route as DefaultLayoutSlugOrIdImageDotwebpRouteImport } from './routes/_default-layout/$slugOrId/image[.]webp'
import { Route as DebugLayoutSlugOrIdDebugRouteImport } from './routes/_debug-layout/$slugOrId/debug'

const DefaultLayoutRouteRoute = DefaultLayoutRouteRouteImport.update({
  id: '/_default-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutRouteRoute = DebugLayoutRouteRouteImport.update({
  id: '/_debug-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRouteRoute,
} as any)
const PlaygroundSsrRoute = PlaygroundSsrRouteImport.update({
  id: '/playground/ssr',
  path: '/playground/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundOgImageRoute = PlaygroundOgImageRouteImport.update({
  id: '/playground/og-image',
  path: '/playground/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutDebugRoute = DebugLayoutDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DebugLayoutRouteRoute,
} as any)
const DefaultLayoutSlugOrIdIndexRoute =
  DefaultLayoutSlugOrIdIndexRouteImport.update({
    id: '/$slugOrId/',
    path: '/$slugOrId/',
    getParentRoute: () => DefaultLayoutRouteRoute,
  } as any)
const DefaultLayoutSlugOrIdImageDotwebpRoute =
  DefaultLayoutSlugOrIdImageDotwebpRouteImport.update({
    id: '/$slugOrId/image.webp',
    path: '/$slugOrId/image.webp',
    getParentRoute: () => DefaultLayoutRouteRoute,
  } as any)
const DebugLayoutSlugOrIdDebugRoute =
  DebugLayoutSlugOrIdDebugRouteImport.update({
    id: '/$slugOrId/debug',
    path: '/$slugOrId/debug',
    getParentRoute: () => DebugLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/$slugOrId/debug': typeof DebugLayoutSlugOrIdDebugRoute
  '/$slugOrId/image.webp': typeof DefaultLayoutSlugOrIdImageDotwebpRoute
  '/$slugOrId/': typeof DefaultLayoutSlugOrIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/$slugOrId/debug': typeof DebugLayoutSlugOrIdDebugRoute
  '/$slugOrId/image.webp': typeof DefaultLayoutSlugOrIdImageDotwebpRoute
  '/$slugOrId': typeof DefaultLayoutSlugOrIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_debug-layout': typeof DebugLayoutRouteRouteWithChildren
  '/_default-layout': typeof DefaultLayoutRouteRouteWithChildren
  '/_debug-layout/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/_default-layout/': typeof DefaultLayoutIndexRoute
  '/_debug-layout/$slugOrId/debug': typeof DebugLayoutSlugOrIdDebugRoute
  '/_default-layout/$slugOrId/image.webp': typeof DefaultLayoutSlugOrIdImageDotwebpRoute
  '/_default-layout/$slugOrId/': typeof DefaultLayoutSlugOrIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/$slugOrId/debug'
    | '/$slugOrId/image.webp'
    | '/$slugOrId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/$slugOrId/debug'
    | '/$slugOrId/image.webp'
    | '/$slugOrId'
  id:
    | '__root__'
    | '/_debug-layout'
    | '/_default-layout'
    | '/_debug-layout/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/_default-layout/'
    | '/_debug-layout/$slugOrId/debug'
    | '/_default-layout/$slugOrId/image.webp'
    | '/_default-layout/$slugOrId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DebugLayoutRouteRoute: typeof DebugLayoutRouteRouteWithChildren
  DefaultLayoutRouteRoute: typeof DefaultLayoutRouteRouteWithChildren
  PlaygroundOgImageRoute: typeof PlaygroundOgImageRoute
  PlaygroundSsrRoute: typeof PlaygroundSsrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default-layout': {
      id: '/_default-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout': {
      id: '/_debug-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DebugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default-layout/': {
      id: '/_default-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/playground/ssr': {
      id: '/playground/ssr'
      path: '/playground/ssr'
      fullPath: '/playground/ssr'
      preLoaderRoute: typeof PlaygroundSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/og-image': {
      id: '/playground/og-image'
      path: '/playground/og-image'
      fullPath: '/playground/og-image'
      preLoaderRoute: typeof PlaygroundOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout/debug': {
      id: '/_debug-layout/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLayoutDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
    '/_default-layout/$slugOrId/': {
      id: '/_default-layout/$slugOrId/'
      path: '/$slugOrId'
      fullPath: '/$slugOrId/'
      preLoaderRoute: typeof DefaultLayoutSlugOrIdIndexRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/_default-layout/$slugOrId/image.webp': {
      id: '/_default-layout/$slugOrId/image.webp'
      path: '/$slugOrId/image.webp'
      fullPath: '/$slugOrId/image.webp'
      preLoaderRoute: typeof DefaultLayoutSlugOrIdImageDotwebpRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/_debug-layout/$slugOrId/debug': {
      id: '/_debug-layout/$slugOrId/debug'
      path: '/$slugOrId/debug'
      fullPath: '/$slugOrId/debug'
      preLoaderRoute: typeof DebugLayoutSlugOrIdDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
  }
}

interface DebugLayoutRouteRouteChildren {
  DebugLayoutDebugRoute: typeof DebugLayoutDebugRoute
  DebugLayoutSlugOrIdDebugRoute: typeof DebugLayoutSlugOrIdDebugRoute
}

const DebugLayoutRouteRouteChildren: DebugLayoutRouteRouteChildren = {
  DebugLayoutDebugRoute: DebugLayoutDebugRoute,
  DebugLayoutSlugOrIdDebugRoute: DebugLayoutSlugOrIdDebugRoute,
}

const DebugLayoutRouteRouteWithChildren =
  DebugLayoutRouteRoute._addFileChildren(DebugLayoutRouteRouteChildren)

interface DefaultLayoutRouteRouteChildren {
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
  DefaultLayoutSlugOrIdImageDotwebpRoute: typeof DefaultLayoutSlugOrIdImageDotwebpRoute
  DefaultLayoutSlugOrIdIndexRoute: typeof DefaultLayoutSlugOrIdIndexRoute
}

const DefaultLayoutRouteRouteChildren: DefaultLayoutRouteRouteChildren = {
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
  DefaultLayoutSlugOrIdImageDotwebpRoute:
    DefaultLayoutSlugOrIdImageDotwebpRoute,
  DefaultLayoutSlugOrIdIndexRoute: DefaultLayoutSlugOrIdIndexRoute,
}

const DefaultLayoutRouteRouteWithChildren =
  DefaultLayoutRouteRoute._addFileChildren(DefaultLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DebugLayoutRouteRoute: DebugLayoutRouteRouteWithChildren,
  DefaultLayoutRouteRoute: DefaultLayoutRouteRouteWithChildren,
  PlaygroundOgImageRoute: PlaygroundOgImageRoute,
  PlaygroundSsrRoute: PlaygroundSsrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
