/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultLayoutRouteRouteImport } from './routes/_default-layout/route'
import { Route as DebugLayoutRouteRouteImport } from './routes/_debug-layout/route'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_default-layout/index'
import { Route as PlaygroundSsrRouteImport } from './routes/playground/ssr'
import { Route as PlaygroundOgImageRouteImport } from './routes/playground/og-image'
import { Route as DebugLayoutDebugRouteImport } from './routes/_debug-layout/debug'
import { Route as DefaultLayoutPostPageIdIndexRouteImport } from './routes/_default-layout/post/$pageId/index'
import { Route as DefaultLayoutPostPageIdImageRouteImport } from './routes/_default-layout/post/$pageId/image'
import { Route as DebugLayoutPostPageIdDebugRouteImport } from './routes/_debug-layout/post/$pageId/debug'

const DefaultLayoutRouteRoute = DefaultLayoutRouteRouteImport.update({
  id: '/_default-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutRouteRoute = DebugLayoutRouteRouteImport.update({
  id: '/_debug-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRouteRoute,
} as any)
const PlaygroundSsrRoute = PlaygroundSsrRouteImport.update({
  id: '/playground/ssr',
  path: '/playground/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundOgImageRoute = PlaygroundOgImageRouteImport.update({
  id: '/playground/og-image',
  path: '/playground/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLayoutDebugRoute = DebugLayoutDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DebugLayoutRouteRoute,
} as any)
const DefaultLayoutPostPageIdIndexRoute =
  DefaultLayoutPostPageIdIndexRouteImport.update({
    id: '/post/$pageId/',
    path: '/post/$pageId/',
    getParentRoute: () => DefaultLayoutRouteRoute,
  } as any)
const DefaultLayoutPostPageIdImageRoute =
  DefaultLayoutPostPageIdImageRouteImport.update({
    id: '/post/$pageId/image',
    path: '/post/$pageId/image',
    getParentRoute: () => DefaultLayoutRouteRoute,
  } as any)
const DebugLayoutPostPageIdDebugRoute =
  DebugLayoutPostPageIdDebugRouteImport.update({
    id: '/post/$pageId/debug',
    path: '/post/$pageId/debug',
    getParentRoute: () => DebugLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
  '/post/$pageId/': typeof DefaultLayoutPostPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultLayoutIndexRoute
  '/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
  '/post/$pageId': typeof DefaultLayoutPostPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_debug-layout': typeof DebugLayoutRouteRouteWithChildren
  '/_default-layout': typeof DefaultLayoutRouteRouteWithChildren
  '/_debug-layout/debug': typeof DebugLayoutDebugRoute
  '/playground/og-image': typeof PlaygroundOgImageRoute
  '/playground/ssr': typeof PlaygroundSsrRoute
  '/_default-layout/': typeof DefaultLayoutIndexRoute
  '/_debug-layout/post/$pageId/debug': typeof DebugLayoutPostPageIdDebugRoute
  '/_default-layout/post/$pageId/image': typeof DefaultLayoutPostPageIdImageRoute
  '/_default-layout/post/$pageId/': typeof DefaultLayoutPostPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/post/$pageId/debug'
    | '/post/$pageId/image'
    | '/post/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/post/$pageId/debug'
    | '/post/$pageId/image'
    | '/post/$pageId'
  id:
    | '__root__'
    | '/_debug-layout'
    | '/_default-layout'
    | '/_debug-layout/debug'
    | '/playground/og-image'
    | '/playground/ssr'
    | '/_default-layout/'
    | '/_debug-layout/post/$pageId/debug'
    | '/_default-layout/post/$pageId/image'
    | '/_default-layout/post/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DebugLayoutRouteRoute: typeof DebugLayoutRouteRouteWithChildren
  DefaultLayoutRouteRoute: typeof DefaultLayoutRouteRouteWithChildren
  PlaygroundOgImageRoute: typeof PlaygroundOgImageRoute
  PlaygroundSsrRoute: typeof PlaygroundSsrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default-layout': {
      id: '/_default-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout': {
      id: '/_debug-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DebugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default-layout/': {
      id: '/_default-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/playground/ssr': {
      id: '/playground/ssr'
      path: '/playground/ssr'
      fullPath: '/playground/ssr'
      preLoaderRoute: typeof PlaygroundSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/og-image': {
      id: '/playground/og-image'
      path: '/playground/og-image'
      fullPath: '/playground/og-image'
      preLoaderRoute: typeof PlaygroundOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug-layout/debug': {
      id: '/_debug-layout/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLayoutDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
    '/_default-layout/post/$pageId/': {
      id: '/_default-layout/post/$pageId/'
      path: '/post/$pageId'
      fullPath: '/post/$pageId/'
      preLoaderRoute: typeof DefaultLayoutPostPageIdIndexRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/_default-layout/post/$pageId/image': {
      id: '/_default-layout/post/$pageId/image'
      path: '/post/$pageId/image'
      fullPath: '/post/$pageId/image'
      preLoaderRoute: typeof DefaultLayoutPostPageIdImageRouteImport
      parentRoute: typeof DefaultLayoutRouteRoute
    }
    '/_debug-layout/post/$pageId/debug': {
      id: '/_debug-layout/post/$pageId/debug'
      path: '/post/$pageId/debug'
      fullPath: '/post/$pageId/debug'
      preLoaderRoute: typeof DebugLayoutPostPageIdDebugRouteImport
      parentRoute: typeof DebugLayoutRouteRoute
    }
  }
}

interface DebugLayoutRouteRouteChildren {
  DebugLayoutDebugRoute: typeof DebugLayoutDebugRoute
  DebugLayoutPostPageIdDebugRoute: typeof DebugLayoutPostPageIdDebugRoute
}

const DebugLayoutRouteRouteChildren: DebugLayoutRouteRouteChildren = {
  DebugLayoutDebugRoute: DebugLayoutDebugRoute,
  DebugLayoutPostPageIdDebugRoute: DebugLayoutPostPageIdDebugRoute,
}

const DebugLayoutRouteRouteWithChildren =
  DebugLayoutRouteRoute._addFileChildren(DebugLayoutRouteRouteChildren)

interface DefaultLayoutRouteRouteChildren {
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
  DefaultLayoutPostPageIdImageRoute: typeof DefaultLayoutPostPageIdImageRoute
  DefaultLayoutPostPageIdIndexRoute: typeof DefaultLayoutPostPageIdIndexRoute
}

const DefaultLayoutRouteRouteChildren: DefaultLayoutRouteRouteChildren = {
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
  DefaultLayoutPostPageIdImageRoute: DefaultLayoutPostPageIdImageRoute,
  DefaultLayoutPostPageIdIndexRoute: DefaultLayoutPostPageIdIndexRoute,
}

const DefaultLayoutRouteRouteWithChildren =
  DefaultLayoutRouteRoute._addFileChildren(DefaultLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DebugLayoutRouteRoute: DebugLayoutRouteRouteWithChildren,
  DefaultLayoutRouteRoute: DefaultLayoutRouteRouteWithChildren,
  PlaygroundOgImageRoute: PlaygroundOgImageRoute,
  PlaygroundSsrRoute: PlaygroundSsrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
